### ISSUE TITLE
Use Zappr, please?

### ISSUE THREAD

**Issue by ePaul** [zalando-stups/odd#8]
Hi,

we get regularly violations for our AWS accounts because of some non-compliants commits in this project being merged. I think this should be avoidable by setting up [Zappr](https://zappr.opensource.zalan.do/) for this Github project (and configuring it correctly).

**Comment by hjacobs** [comment]
While using Zappr makes sense, honestly your violations are not caused by this.

**Comment by ePaul** [comment]
Hmm, the violation message is saying

> MISSING_SPEC_LINKS
> 
> Some Git commits do not contain valid references to the issue tracking system.

and mentioning commit be0a4b4dba4c94f10109023e6f474bbe48ad00ed. Would this not be prevented by having Zappr here?

**Comment by hjacobs** [comment]
@ePaul no, the `MISSING_SPEC_LINKS` is an "old" violation about commit messages having some issue reference (e.g. Jira ticket number). The issue is that Fullstop does not know that your AWS account is running an app (Odd) which uses the Github approval flow.

**Comment by ePaul** [comment]
Hmm, actually odd is not yet using the Github approval flow (that is what this issue is about). But if you say that it wouldn't help (because even with the Github approval flow, it would still have no issue reference), I'll simply accept this fact.
